# Generated by Django 3.2.20 on 2023-08-07 01:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('status', models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivado')], max_length=10, verbose_name='estado')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(max_length=255, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='photos/products', verbose_name='imagen')),
                ('price', models.IntegerField(default=0, verbose_name='precio')),
                ('compare_price', models.IntegerField(default=0, verbose_name='compare precio')),
                ('stock', models.IntegerField(default=0)),
                ('minstock', models.IntegerField(default=3)),
                ('variant', models.CharField(choices=[('None', 'Ninguna'), ('Size', 'Talla'), ('Color', 'Color'), ('Size-Color', 'Talla-Color'), ('Landing', 'Landing')], default='None', max_length=10, verbose_name='variante')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='detalles')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivado')], max_length=10, verbose_name='estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='talla')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('image', models.ImageField(blank=True, upload_to='photos/products', verbose_name='imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
