# Generated by Django 3.2.20 on 2023-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivado')], max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'Ninguna'), ('Size', 'Talla'), ('Color', 'Color'), ('Size-Color', 'Talla-Color'), ('Landing', 'Landing')], default='None', max_length=30, verbose_name='variante'),
        ),
    ]
