# Generated by Django 3.2.20 on 2023-08-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230811_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='size',
            new_name='size_id',
        ),
    ]
