# Generated by Django 3.2.20 on 2023-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230811_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='size_id',
        ),
        migrations.AddField(
            model_name='variants',
            name='size_id',
            field=models.ManyToManyField(to='product.Size', verbose_name='talla'),
        ),
    ]
