# Generated by Django 3.2.20 on 2023-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230811_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='size_id',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='product.Size', verbose_name='talla'),
        ),
    ]
