# Generated by Django 3.2.20 on 2023-08-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_variants_size_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.images'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size_id',
            field=models.ManyToManyField(blank=True, related_name='variants_sizes', to='product.Size', verbose_name='talla'),
        ),
    ]
