# Generated by Django 3.2.20 on 2023-08-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230812_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='product.category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(True, 'Activo'), (False, 'Desactivado')], default=True, max_length=20, verbose_name='estado'),
        ),
    ]
