# Generated by Django 3.2.20 on 2023-08-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations_colors',
            new_name='variations_colors_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations_sizes',
            new_name='variations_sizes_id',
        ),
    ]
