# Generated by Django 3.2.20 on 2023-08-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230807_1740'),
        ('cart', '0002_auto_20230810_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations_colors_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='colores'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations_sizes_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='tamaños'),
        ),
    ]
