# Generated by Django 3.2.20 on 2023-08-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230811_2015'),
        ('cart', '0004_alter_cartitem_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations_colors_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='product.color', verbose_name='colores'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations_sizes_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='tamaños'),
        ),
    ]
