# Generated by Django 3.2.20 on 2023-08-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230812_1911'),
        ('cart', '0005_auto_20230811_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variations_colors_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variations_sizes_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variants', verbose_name='variante'),
        ),
    ]
