# Generated by Django 3.2.20 on 2023-08-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20230812_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variant',
            new_name='variant_id',
        ),
    ]
