# Generated by Django 3.2.20 on 2023-08-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_variant_cartitem_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('True', 'Activo'), ('False', 'Desactivado')], default='True', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, max_length=250, primary_key=True, serialize=False),
        ),
    ]
