# Generated by Django 3.2.20 on 2023-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20230825_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[(True, 'Activo'), (False, 'Desactivado')], default=True, max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[(True, 'Activo'), (False, 'Desactivado')], default=True, max_length=20, verbose_name='estado'),
        ),
    ]
