# Generated by Django 3.2.20 on 2023-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20230826_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desactivado')], default='active', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desactivado')], default='active', max_length=20, verbose_name='estado'),
        ),
    ]
